# Generated by Django 3.1.2 on 2020-10-03 23:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirNowForecastSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AirNowReportingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('state_code', models.CharField(max_length=2)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='AirNowReportingAreaZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField(db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='AirNowObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField()),
                ('valid_date', models.DateField()),
                ('valid_time', models.TimeField(null=True)),
                ('record_sequence', models.SmallIntegerField()),
                ('parameter_name', models.CharField(max_length=10)),
                ('aqi_value', models.SmallIntegerField(null=True)),
                ('aqi_category', models.CharField(max_length=40)),
                ('primary_pollutant', models.BooleanField()),
                ('type', models.CharField(choices=[('F', 'Forecast'), ('Y', 'Yesterday'), ('O', 'Hourly Observation')], max_length=1)),
                ('discussion', models.CharField(max_length=500)),
                ('reporting_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airnowreportingarea')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airnowforecastsource')),
            ],
        ),
    ]
