# Generated by Django 3.1.2 on 2020-10-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_airnowforecastsource_airnowobservation_airnowreportingarea_airnowreportingareazipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airnowobservation',
            name='valid_time',
        ),
        migrations.AlterField(
            model_name='airnowreportingareazipcode',
            name='zipcode',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
