# Generated by Django 3.1.2 on 2020-10-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201004_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airnowreportingarea',
            name='name',
            field=models.CharField(db_index=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='airnowreportingarea',
            name='state_code',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AddIndex(
            model_name='airnowreportingarea',
            index=models.Index(fields=['name', 'state_code'], name='api_airnowr_name_3a07e3_idx'),
        ),
    ]
