# Generated by Django 3.1.2 on 2020-10-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201004_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airnowobservation',
            name='valid_date',
            field=models.DateTimeField(),
        ),
    ]
