# Generated by Django 3.1.2 on 2020-10-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201004_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airnowobservation',
            name='discussion',
            field=models.TextField(null=True),
        ),
    ]
