# Generated by Django 3.1.2 on 2020-10-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201004_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airnowobservation',
            name='issued_date',
            field=models.DateTimeField(),
        ),
    ]
